### ISSUE TITLE
Api Routes

### ISSUE THREAD

**Issue by jrmessias** [andrey-helldar/pretty-routes#17]
- Pretty Route Version: 1.19.0
- Laravel Version: 6.20.4
- PHP Version: 7.4.12

### Description:
Can I show routes for API?

**Comment by andrey-helldar** [comment]
You can get a list of all routes using the Laravel API:
`Illuminate\Support\Facades\Route::getRoutes()`

Or do you want to get a list of routes processed for this package?
If yes, then refer to the method:
```
use Helldar\LaravelRoutesCore\Support\Routes;

$routes = new Routes();

return $routes->collection();
```

See: https://github.com/andrey-helldar/laravel-routes-core/blob/master/src/Support/Routes.php#L22

**Comment by andrey-helldar** [comment]
Or are you asking about the ability to filter routes by API?
If so, now their general list is displayed regardless of the purpose, but I can add a filter for them tomorrow.

**Comment by andrey-helldar** [comment]
Version `v1.20.0` has been released.

> Principle: All text is searched, including route, method type, route name, controller, module, and middlewares.

There are several ways to get the filtered list for the API:

### Option 1
Enter "api" in the search field.

### Option 2
Click on middleware api.

This action will insert the middleware into the search box and instantly filter the list.

![image](https://user-images.githubusercontent.com/10347617/100334054-5466bc00-2fe4-11eb-8bc1-8139119fcac0.png)

### Option 3
Specify the names of middleware for web and api in the settings.
They are initially used to display the / routes page and ajax request a list of routes.
Starting from version `1.20.0`, they are also used to determine the route type label (api / web).

Added filter by type to toolbar:

![image](https://user-images.githubusercontent.com/10347617/100334304-a871a080-2fe4-11eb-8dcd-b36df8288119.png)
