### ISSUE TITLE
Problem with js file

### ISSUE THREAD

**Issue by xelyos94ro** [andrey-helldar/pretty-routes#18]
- Pretty Route Version: 1.21
- Laravel Version: 8
- PHP Version: 8.0

### Description:
the js file is not available on https://cdn.jsdelivr.net/gh/andrey-helldar/pretty-routes-frontend@1.21/dist/app.js

### Steps To Reproduce:
I just replace the old package with the new one and the js file is not available on cdn jsdelivr

**Comment by andrey-helldar** [comment]
Fixed [v1.21.2](https://github.com/andrey-helldar/pretty-routes/releases/tag/v1.21.2) and released.
