### ISSUE TITLE
What do you think if refresh button execute artisan route:clear?

### ISSUE THREAD

**Issue by ifaniqbal** [andrey-helldar/pretty-routes#20]
Great package.

This is not issue.

**Comment by andrey-helldar** [comment]
Hi!

I think that caching routes on the production server is an important consideration in improving application performance.

Although this package is intended for developers, some may use it in production as well, protecting routes by [middlewares](https://github.com/andrey-helldar/pretty-routes/blob/master/config/pretty-routes.php#L10-L14) authorization.

Thus, it is best not to add route cleanup to the refresh button.

**BUT** I can add another button next to it specifically for cleaning routes and it will only be displayed on the dev environment.

I will do this in the coming days.

**Comment by andrey-helldar** [comment]
Released in [v1.22.0](https://github.com/andrey-helldar/pretty-routes/releases/tag/v1.22.0)
