### ISSUE TITLE
PHPDocumentor issue

### ISSUE THREAD

**Issue by mochokoro** [andrey-helldar/pretty-routes#36]
"phpdocumentor/type-resolver": "^1.1.0"

Request failed with status code 500
{
  "message": "A type is missing after a type separator",
  "exception": "RuntimeException",
  "file": "path/vendor/phpdocumentor/type-resolver/src/TypeResolver.php",
  "line": 273,
  "trace": [
    {
      "file": "path/vendor/phpdocumentor/type-resolver/src/TypeResolver.php",
      "line": 155,
      "function": "parseTypes",
      "class": "phpDocumentor\\Reflection\\TypeResolver",
      "type": "->"
    },
    {
      "file": "path/vendor/phpdocumentor/reflection-docblock/src/DocBlock/Tags/Return_.php",
      "line": 46,
      "function": "resolve",
      "class": "phpDocumentor\\Reflection\\TypeResolver",
      "type": "->"
    },
    {
      "file": "path/vendor/phpdocumentor/reflection-docblock/src/DocBlock/StandardTagFactory.php",
      "line": 216,
      "function": "create",
      "class": "phpDocumentor\\Reflection\\DocBlock\\Tags\\Return_",
      "type": "::"
    },
    {
      "file": "path/vendor/phpdocumentor/reflection-docblock/src/DocBlock/StandardTagFactory.php",
      "line": 148,
      "function": "createTag",
      "class": "phpDocumentor\\Reflection\\DocBlock\\StandardTagFactory",
      "type": "->"
    },
    {
      "file": "path/vendor/phpdocumentor/reflection-docblock/src/DocBlockFactory.php",
      "line": 244,
      "function": "create",
      "class": "phpDocumentor\\Reflection\\DocBlock\\StandardTagFactory",
      "type": "->"
    },
    {
      "file": "path/vendor/phpdocumentor/reflection-docblock/src/DocBlockFactory.php",
      "line": 104,
      "function": "parseTagBlock",
      "class": "phpDocumentor\\Reflection\\DocBlockFactory",
      "type": "->"
    },
    {
      "file": "path/vendor/andrey-helldar/laravel-routes-core/src/Models/Reader.php",
      "line": 63,
      "function": "create",
      "class": "phpDocumentor\\Reflection\\DocBlockFactory",
      "type": "->"
    },
    {
      "file": "path/vendor/andrey-helldar/laravel-routes-core/src/Models/Reader.php",
      "line": 51,
      "function": "get",
      "class": "Helldar\\LaravelRoutesCore\\Models\\Reader",
      "type": "->"
    },
    {
      "file": "path/vendor/andrey-helldar/laravel-routes-core/src/Support/Annotation.php",
      "line": 112,
      "function": "forMethod",
      "class": "Helldar\\LaravelRoutesCore\\Models\\Reader",
      "type": "->"
    },
    {
      "file": "path/vendor/andrey-helldar/laravel-routes-core/src/Support/Annotation.php",
      "line": 106,
      "function": "getValue",
      "class": "Helldar\\LaravelRoutesCore\\Support\\Annotation",
      "type": "->"
    },
    {
      "file": "path/vendor/andrey-helldar/laravel-routes-core/src/Support/Annotation.php",
      "line": 48,
      "function": "get",
      "class": "Helldar\\LaravelRoutesCore\\Support\\Annotation",
      "type": "->"
    },
    {
      "file": "path/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php",
      "line": 261,
      "function": "isDeprecated",
      "class": "Helldar\\LaravelRoutesCore\\Support\\Annotation",
      "type": "->"
    },
    {
      "file": "path/vendor/andrey-helldar/laravel-routes-core/src/Models/Route.php",
      "line": 170,
      "function": "__callStatic",
      "class": "Illuminate\\Support\\Facades\\Facade",
      "type": "::"
    },
    {
      "file": "path/vendor/andrey-helldar/laravel-routes-core/src/Models/Route.php",
      "line": 204,
      "function": "getDeprecated",
      "class": "Helldar\\LaravelRoutesCore\\Models\\Route",
      "type": "->"
    },
    {
      "file": "path/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php",
      "line": 833,
      "function": "toArray",
      "class": "Helldar\\LaravelRoutesCore\\Models\\Route",
      "type": "->"
    },
    {
      "function": "Illuminate\\Support\\Traits\\{closure}",
      "class": "Illuminate\\Support\\Collection",
      "type": "->"
    },
    {
      "file": "path/vendor/laravel/framework/src/Illuminate/Collections/Collection.php",
      "line": 640,
      "function": "array_map"
    },
    {
      "file": "path/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php",
      "line": 834,
      "function": "map",
      "class": "Illuminate\\Support\\Collection",
      "type": "->"
    },
    {
      "file": "path/vendor/andrey-helldar/laravel-routes-core/src/Support/Routes.php",
      "line": 49,
      "function": "toArray",
      "class": "Illuminate\\Support\\Collection",
      "type": "->"
    },
    {
      "file": "path/vendor/andrey-helldar/pretty-routes/src/Http/PrettyRoutesController.php",
      "line": 37,
      "function": "get",
      "class": "Helldar\\LaravelRoutesCore\\Support\\Routes",
      "type": "->"
    },
    {
      "file": "path/vendor/laravel/framework/src/Illuminate/Routing/Controller.php",
      "line": 54,
      "function": "routes",
      "class": "PrettyRoutes\\Http\\PrettyRoutesController",
      "type": "->"
    },
    {
      "file": "path/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php",
      "line": 45,
      "function": "callAction",
      "class": "Illuminate\\Routing\\Controller",
      "type": "->"
    },
    {
      "file": "path/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
      "line": 254,
      "function": "dispatch",
      "class": "Illuminate\\Routing\\ControllerDispatcher",
      "type": "->"
    },
    {
      "file": "path/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
      "line": 197,
      "function": "runController",
      "class": "Illuminate\\Routing\\Route",
      "type": "->"
    },
    {
      "file": "path/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
      "line": 693,
      "function": "run",
      "class": "Illuminate\\Routing\\Route",
      "type": "->"
    },
    {
      "file": "path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 128,
      "function": "Illuminate\\Routing\\{closure}",
      "class": "Illuminate\\Routing\\Router",
      "type": "->"
    },
    {
      "file": "path/platform/packages/api/src/Http/Middleware/ForceJsonResponseMiddleware.php",
      "line": 21,
      "function": "Illuminate\\Pipeline\\{closure}",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 167,
      "function": "handle",
      "class": "Simtabi\\Api\\Http\\Middleware\\ForceJsonResponseMiddleware",
      "type": "->"
    },
    {
      "file": "path/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php",
      "line": 50,
      "function": "Illuminate\\Pipeline\\{closure}",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 167,
      "function": "handle",
      "class": "Illuminate\\Routing\\Middleware\\SubstituteBindings",
      "type": "->"
    },
    {
      "file": "path/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php",
      "line": 127,
      "function": "Illuminate\\Pipeline\\{closure}",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "path/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php",
      "line": 103,
      "function": "handleRequest",
      "class": "Illuminate\\Routing\\Middleware\\ThrottleRequests",
      "type": "->"
    },
    {
      "file": "path/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php",
      "line": 55,
      "function": "handleRequestUsingNamedLimiter",
      "class": "Illuminate\\Routing\\Middleware\\ThrottleRequests",
      "type": "->"
    },
    {
      "file": "path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 167,
      "function": "handle",
      "class": "Illuminate\\Routing\\Middleware\\ThrottleRequests",
      "type": "->"
    },
    {
      "file": "path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 103,
      "function": "Illuminate\\Pipeline\\{closure}",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "path/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
      "line": 695,
      "function": "then",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "path/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
      "line": 670,
      "function": "runRouteWithinStack",
      "class": "Illuminate\\Routing\\Router",
      "type": "->"
    },
    {
      "file": "path/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
      "line": 636,
      "function": "runRoute",
      "class": "Illuminate\\Routing\\Router",
      "type": "->"
    },
    {
      "file": "path/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
      "line": 625,
      "function": "dispatchToRoute",
      "class": "Illuminate\\Routing\\Router",
      "type": "->"
    },
    {
      "file": "path/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
      "line": 166,
      "function": "dispatch",
      "class": "Illuminate\\Routing\\Router",
      "type": "->"
    },
    {
      "file": "path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 128,
      "function": "Illuminate\\Foundation\\Http\\{closure}",
      "class": "Illuminate\\Foundation\\Http\\Kernel",
      "type": "->"
    },
    {
      "file": "path/platform/core/js-validation/src/RemoteValidationMiddleware.php",
      "line": 61,
      "function": "Illuminate\\Pipeline\\{closure}",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 167,
      "function": "handle",
      "class": "Simtabi\\JsValidation\\RemoteValidationMiddleware",
      "type": "->"
    },
    {
      "file": "path/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php",
      "line": 67,
      "function": "Illuminate\\Pipeline\\{closure}",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 167,
      "function": "handle",
      "class": "Barryvdh\\Debugbar\\Middleware\\InjectDebugbar",
      "type": "->"
    },
    {
      "file": "path/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
      "line": 21,
      "function": "Illuminate\\Pipeline\\{closure}",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 167,
      "function": "handle",
      "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
      "type": "->"
    },
    {
      "file": "path/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
      "line": 21,
      "function": "Illuminate\\Pipeline\\{closure}",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 167,
      "function": "handle",
      "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
      "type": "->"
    },
    {
      "file": "path/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php",
      "line": 27,
      "function": "Illuminate\\Pipeline\\{closure}",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 167,
      "function": "handle",
      "class": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize",
      "type": "->"
    },
    {
      "file": "path/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php",
      "line": 86,
      "function": "Illuminate\\Pipeline\\{closure}",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 167,
      "function": "handle",
      "class": "Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance",
      "type": "->"
    },
    {
      "file": "path/vendor/fruitcake/laravel-cors/src/HandleCors.php",
      "line": 37,
      "function": "Illuminate\\Pipeline\\{closure}",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 167,
      "function": "handle",
      "class": "Fruitcake\\Cors\\HandleCors",
      "type": "->"
    },
    {
      "file": "path/vendor/fideloper/proxy/src/TrustProxies.php",
      "line": 57,
      "function": "Illuminate\\Pipeline\\{closure}",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 167,
      "function": "handle",
      "class": "Fideloper\\Proxy\\TrustProxies",
      "type": "->"
    },
    {
      "file": "path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 103,
      "function": "Illuminate\\Pipeline\\{closure}",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "path/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
      "line": 141,
      "function": "then",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "path/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
      "line": 110,
      "function": "sendRequestThroughRouter",
      "class": "Illuminate\\Foundation\\Http\\Kernel",
      "type": "->"
    },
    {
      "file": "path/public/index.php",
      "line": 52,
      "function": "handle",
      "class": "Illuminate\\Foundation\\Http\\Kernel",
      "type": "->"
    }
  ]
}

**Comment by andrey-helldar** [comment]
The stack trace reports that the dock block in your code cannot be parsed.
Probably mistakes were made in its writing.
Can you find the problem area of your app and provide its code?
