### ISSUE TITLE
Request failed with status code 500

### ISSUE THREAD

**Issue by poseso** [andrey-helldar/pretty-routes#39]
- Pretty Route Version: 2.2.1
- Laravel Version: 8.47.0
- PHP Version: 7.4.2

Request failed with status code 500
Argument 1 passed to Helldar\LaravelRoutesCore\Support\Annotation::Helldar\LaravelRoutesCore\Support\{closure}() must be an instance of phpDocumentor\Reflection\DocBlock\Tags\Return_, instance of phpDocumentor\Reflection\DocBlock\Tags\InvalidTag given

### Steps To Reproduce:

Routes:

Route::prefix('glicemia')->name('glicemia.')->group(function () {
    Route::get('generate-pdf', [GlicemiaController::class, 'pdfview'])->name('generate-pdf')->middleware('permission:glicemia.read');
    Route::post('get', [GlicemiaController::class, 'getDataTables'])->name('get')->middleware('permission:glicemia.read');
    Route::get('/', [GlicemiaController::class, 'index'])->name('index')->middleware('permission:glicemia.read');
    Route::get('create', [GlicemiaController::class, 'create'])->name('create')->middleware('permission:glicemia.create');
    Route::post('create', [GlicemiaController::class, 'store'])->name('store')->middleware('permission:glicemia.create');
    Route::get('show/{glicemia}', [GlicemiaController::class, 'show'])->name('show')->middleware('permission:glicemia.read');

<-- HERE it throws the error -->
    Route::get('edit/{glicemia}', [GlicemiaController::class, 'edit'])->name('edit')->middleware('permission:glicemia.update');
    Route::patch('edit/{glicemia}', [GlicemiaController::class, 'update'])->name('update')->middleware('permission:glicemia.update');
    Route::delete('destroy/{glicemia}', [GlicemiaController::class, 'destroy'])->name('destroy')->middleware('permission:glicemia.delete');
});

Even though i can access the routes and works as expected its throwing that error, is there anything i should look into?

Thanks

**Comment by andrey-helldar** [comment]
Show doc-block from `GlicemiaController@edit` method.

**Comment by andrey-helldar** [comment]
@Barmunksu, show your dock-block recording that is causing the error.
