### ISSUE TITLE
Request failed with status code 500

### ISSUE THREAD

**Issue by Barmunksu** [andrey-helldar/pretty-routes#40]
laravel 6

Argument 1 passed to Helldar\LaravelRoutesCore\Support\Annotation::Helldar\LaravelRoutesCore\Support\{closure}() must be an instance of phpDocumentor\Reflection\DocBlock\Tags\Return_, instance of phpDocumentor\Reflection\DocBlock\Tags\InvalidTag given

>{
  "message": "Argument 1 passed to Helldar\\LaravelRoutesCore\\Support\\Annotation::Helldar\\LaravelRoutesCore\\Support\\{closure}() must be an instance of phpDocumentor\\Reflection\\DocBlock\\Tags\\Return_, instance of phpDocumentor\\Reflection\\DocBlock\\Tags\\InvalidTag given",
  "exception": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError",
  "file": "C:\\OSPanel\\domains\\localhost\\vendor\\andrey-helldar\\laravel-routes-core\\src\\Support\\Annotation.php",
  "line": 89,
  "trace": [
    {
      "function": "Helldar\\LaravelRoutesCore\\Support\\{closure}",
      "class": "Helldar\\LaravelRoutesCore\\Support\\Annotation",
      "type": "::"
    },
    {
      "file": "C:\\OSPanel\\domains\\localhost\\vendor\\andrey-helldar\\laravel-routes-core\\src\\Support\\Annotation.php",
      "line": 91,
      "function": "array_map"
    },
......

**Comment by andrey-helldar** [comment]
See https://github.com/andrey-helldar/pretty-routes/issues/39
